# --- CONFIGURATION RESILIENCE4J (Cas 2.f) ---
mes-config-ms.commandes-last=20
# Timeout de 500ms
resilience4j.timelimiter.instances.microservice-produits.timeout-duration=500ms
resilience4j.timelimiter.instances.microservice-produits.cancel-running-future=true

# Paramètres du disjoncteur
resilience4j.circuitbreaker.instances.microservice-produits.sliding-window-size=10
resilience4j.circuitbreaker.instances.microservice-produits.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.microservice-produits.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.microservice-produits.permitted-number-of-calls-in-half-open-state=3
